# 스프링부트 프로젝트를 실행시킬때 nohup java -jar -Dspring.profiles.active=set1와 같이 사용하면 set1에 있는 값들이 프로젝트에 할당됩니다.

spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
  mustache:
    expose-session-attributes: true   #뷰페이지에서 session에 담긴 정보 가져올때 필요함

upload:
  path: C:\Users\sehyu\IdeaProjects\spring-webservice\src\main\resources\static\image

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

spring:
  thymeleaf:
    prefix: classpath:/templates

upload:
  path: classpath:/templates

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082

spring:
  thymeleaf:
    prefix: classpath:/templates